stages:
  - deploy

deploy:
  image: ubuntu:latest
  stage: deploy
  before_script:
    - apt update
    - apt upgrade
    - apt install openssh-client -y
    - install -m 600 -D /dev/null ~/.ssh/cicd
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/cicd
    - ssh-keyscan -H -p $SSH_PORT $SSH_HOST > ~/.ssh/known_hosts
  script:
    - ssh -i ~/.ssh/cicd -p $SSH_PORT $SSH_USER@$SSH_HOST '(&>/dev/null bash -s < /scripts/restart-testprod.sh &)'

  after_script:
    - rm -rf ~/.ssh
    - history -r
