services:
  fullstack-website:
    image: cicd-registry.devdoes.work/rps-developers/rps-tournament:cicd-${CI_COMMIT_SHORT_SHA}

    ports:
      - 5176:5173

    deploy:
      replicas: 3
      update_config:
        order: start-first

        #secrets:
        #  rps-port:
        #    external: true
